name: Vulnerability Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Vulnerability Check
      uses: dhcs/whitesource-scan@0.0.32
      with:
        orb: dhcs/whitesource-scan@0.0.32
        command: run
